version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  target-branch: main
- package-ecosystem: npm
  directory: "/webapp/"
  schedule:
    interval: monthly
  target-branch: main
