name: Release

on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ "main", "next" ]
    types:
      - completed

jobs:
  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.TOLGEE_MACHINE_PAT }}'

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Set git globals
        run: |
          git config --local user.email "machine@tolgee.io"
          git config --local user.name "Tolgee Machine"

      - name: Install node modules
        run: npm ci

      - name: Run get new version
        run: npm run release-dry

      - name: Set version property
        id: version
        run: echo ::set-output name=VERSION::$(test -e .VERSION && echo v$(cat .VERSION))

      - name: BootJar with version
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: ./gradlew bootJar
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          TOLGEE_API_KEY: ${{secrets.TOLGEE_API_KEY}}
          TOLGEE_API_URL: ${{secrets.TOLGEE_API_URL}}

      - name: Create docker image
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: ./gradlew docker
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          TOLGEE_API_KEY: ${{secrets.TOLGEE_API_KEY}}
          TOLGEE_API_URL: ${{secrets.TOLGEE_API_URL}}

      - name: Pack with webapp
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: ./gradlew packResources
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          TOLGEE_API_KEY: ${{secrets.TOLGEE_API_KEY}}
          TOLGEE_API_URL: ${{secrets.TOLGEE_API_URL}}

      - name: Run npm release
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: npm run release

      - name: Create Release
        if: ${{ steps.version.outputs.VERSION != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          draft: false

      - name: Upload Release Asset
        if: ${{ steps.version.outputs.VERSION != '' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/tolgee-${{ steps.version.outputs.VERSION }}.jar
          asset_name: tolgee-${{ steps.version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Login to docker
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Tag the image
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: |
          docker tag tolgee/tolgee tolgee/tolgee:${{ steps.version.outputs.VERSION }}
          docker tag tolgee/tolgee tolgee/tolgee:latest

      - name: Publish docker image
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: |
          docker push tolgee/tolgee:${{ steps.version.outputs.VERSION }}
          docker push tolgee/tolgee:latest

      - name: Deploy testing
        if: ${{ steps.version.outputs.VERSION != '' }}
        run: |
          mkdir -p ~/.kube
          echo $KUBERNETES_DO_SERVICE_CONFIG | base64 -d > ~/.kube/config
          kubectl exec $(kubectl get pods -l app=testing-migrator -o jsonpath={.items\[0\].metadata.name}) -- /bin/bash -c "MIGRATE_TARGET_IMAGE=tolgee/tolgee:latest /migrate.sh"
        env:
          KUBERNETES_DO_SERVICE_CONFIG: ${{secrets.KUBERNETES_DO_SERVICE_CONFIG}}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test
          path: |
            ./e2e/cypress/videos/**/*
            ./e2e/cypress/screenshots/**/*
            ./build/reports/**/*
